version: "3.8"
services:
    app:
        build:
            context: .
        container_name: symfony_app
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/symfony
        environment:
            - APP_ENV=dev

    db:
        image: mariadb:latest
        container_name: symfony_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - "3307:3306"
