controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'home/index.html.twig'

register:
  path: /register
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  methods: ['GET', 'POST']
  defaults:
    template: 'home/register.html.twig'