controllers:
  resource: '../src/Controller/'
  type: attribute

home:
  path: /
  controller: App\Controller\PagesController::home

events:
  path: /events
  controller: App\Controller\NewsController::events

rules:
  path: /regles
  controller: App\Controller\RulesController::index

register:
  path: /register
  controller: App\Controller\RegisterController::index

news:
  path: /news
  controller: App\Controller\NewsController::listNews

packs:
  path: /packs
  controller: App\Controller\PacksController::index

product_show:
  path: /packs/{id}
  controller: App\Controller\PacksController::show

cards:
  path: /cards
  controller: App\Controller\CardsController::index

admin:
  resource: '../src/Controller/AdminController.php'
  type: attribute