controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

home:
  path: /
  controller: App\Controller\HomeController::index

events:
  path: /events
  controller: App\Controller\NewsController::events

rules:
  path: /regles
  controller: App\Controller\RulesController::index

register:
  path: /register
  controller: App\Controller\RegisterController::index

news:
  path: /news
  controller: App\Controller\NewsController::index

packs:
  path: /packs
  controller: App\Controller\PacksController::index

product_show:
  path: /packs/{id}
  controller: App\Controller\PacksController::show

cards:
  path: /cards
  controller: App\Controller\CardsController::index

show_news:
  path: /news/{id}
  controller: App\Controller\NewsController::show

event_show:
  path: /events/{id}
  controller: App\Controller\NewsController::show

user_account:
  path: /compte
  controller: App\Controller\UserAccountController::index

cart:
  path: /panier
  controller: App\Controller\UserAccountController::cart

order_history:
  path: /historique
  controller: App\Controller\UserAccountController::orderHistory

