controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

home:
  path: /
  controller: App\Controller\HomeController::index

rules:
  path: /regles
  controller: App\Controller\RulesController::index

register:
  path: /register
  controller: App\Controller\RegisterController::index

news:
  path: /news
  controller: App\Controller\NewsController::index
